# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JALearnOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JALearnOC

 pod 'Masonry'
 pod 'MJRefresh'
 pod 'Toast'
 pod 'YYModel', '~> 1.0.4'
 pod 'SVProgressHUD'
 pod 'WMPageController'
 pod 'SuperPlayer'
 pod 'DatabaseVisual'
 pod 'AXWebViewController'
 pod 'FCUUID'
 

  target 'JALearnOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JALearnOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
